In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
from matplotlib import pyplot as plt
import sklearn.datasets
import sklearn.model_selection
import numpy as np
import pandas as pd

/home/lukas/.pyenv/versions/3.8.2/envs/evaluations/lib/python3.8/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


In [3]:
PREDICTIONS_OUT = 'test_pred_proba.csv'
LABELS_OUT = 'test_labels.csv'

## Download dataset

In [4]:
iris = sklearn.datasets.load_digits()

In [5]:
iris.data.shape

(1797, 64)

In [6]:
iris.target[:5]

array([0, 1, 2, 3, 4])

## Split and train

In [7]:
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(iris.data, iris.target)

In [8]:
len(iris.data), len(X_train), len(X_test)

(1797, 1347, 450)

In [9]:
len(iris.target), len(y_train), len(y_test)

(1797, 1347, 450)

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
cls = LogisticRegression()


In [12]:
cls.fit(X_train, y_train)

/home/lukas/.pyenv/versions/3.8.2/envs/evaluations/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
y_pred_proba = cls.predict_proba(X_test)
y_pred_proba[:5]

array([[1.03722642e-08, 3.80526528e-06, 5.59868862e-07, 1.30549694e-03,
        2.86040309e-11, 4.00278323e-01, 1.82703588e-07, 4.71167590e-09,
        5.98315704e-01, 9.59125903e-05],
       [3.73407008e-15, 2.53817693e-12, 1.04599294e-08, 9.99997335e-01,
        8.66399218e-19, 7.45343872e-09, 7.67614504e-16, 3.10171556e-11,
        1.22655165e-08, 2.63491141e-06],
       [2.24229088e-12, 1.97785854e-10, 7.70551946e-16, 3.78027790e-11,
        2.78901074e-10, 9.99999999e-01, 4.04918696e-14, 8.93272894e-10,
        1.00388445e-12, 7.57018992e-11],
       [3.10131847e-10, 4.07834682e-11, 2.52996268e-17, 1.03164925e-21,
        9.99999059e-01, 1.54898519e-13, 4.56553094e-08, 8.95438155e-07,
        2.54167536e-12, 1.28424131e-17],
       [8.08071975e-08, 3.82515762e-15, 2.75675056e-13, 1.94625147e-05,
        6.00107734e-15, 9.99861290e-01, 2.12688436e-08, 1.93458151e-12,
        1.19108350e-04, 3.67605763e-08]])

In [14]:
y_pred = np.argmax(y_pred_proba, axis=1)
y_pred[:5]

array([8, 3, 5, 4, 5])

## Valid

In [15]:
accuracy = sum(y_pred == y_test) / len(y_pred)
print(f'accuracy: {accuracy*100:.1f}%')

accuracy: 96.7%


## Store predictions

In [16]:
y_pred_proba.shape

(450, 10)

In [17]:
pred_proba_df = pd.DataFrame(y_pred_proba, columns=[f'pred_proba_{idx}' for idx in range(y_pred_proba.shape[1])])
print(pred_proba_df.shape)
pred_proba_df.head(3)

(450, 10)


pred_proba_0  pred_proba_1  pred_proba_2  pred_proba_3  pred_proba_4  \
0  1.037226e-08  3.805265e-06  5.598689e-07  1.305497e-03  2.860403e-11   
1  3.734070e-15  2.538177e-12  1.045993e-08  9.999973e-01  8.663992e-19   
2  2.242291e-12  1.977859e-10  7.705519e-16  3.780278e-11  2.789011e-10   

   pred_proba_5  pred_proba_6  pred_proba_7  pred_proba_8  pred_proba_9  
0  4.002783e-01  1.827036e-07  4.711676e-09  5.983157e-01  9.591259e-05  
1  7.453439e-09  7.676145e-16  3.101716e-11  1.226552e-08  2.634911e-06  
2  1.000000e+00  4.049187e-14  8.932729e-10  1.003884e-12  7.570190e-11

In [18]:
print(f'writing labels to: "{LABELS_OUT}"')
pd.Series(y_test, name="label").to_csv(LABELS_OUT, index=False)

writing labels to: "test_labels.csv"


In [19]:
print(f'writing pred_proba to "{PREDICTIONS_OUT}"')
pred_proba_df.to_csv(PREDICTIONS_OUT, index=False)

writing pred_proba to "test_pred_proba.csv"
